spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimrzone=UTC$useUnicode=true&characterEncodeing=utf8
    username: root
    password: 123456
